import * as React from 'react';

export interface IPostProps {}

export default function Post(props: IPostProps) {
  return (
    <>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
      <div>Post here</div>
    </>
  );
}
